# Default Docker Compose - points to development configuration
# Use 'make dev' or 'docker-compose -f docker-compose.dev.yml up' for development
# Use 'make prod' or 'docker-compose -f docker-compose.prod.yml up' for production

version: '3.8'

# This file serves as the default entry point
# For actual configuration, see docker-compose.dev.yml and docker-compose.prod.yml

# Development services (mirrors docker-compose.dev.yml structure)
services:
  oc_database:
    extends:
      file: docker-compose.dev.yml
      service: oc_database

  oc_app:
    extends:
      file: docker-compose.dev.yml
      service: oc_app

  oc_redis:
    extends:
      file: docker-compose.dev.yml
      service: oc_redis

volumes:
  oc_postgres_data_dev:
  oc_redis_data_dev:
  oc_prisma_cache_dev:

networks:
  oc_network_dev:
    driver: bridge