# Prometheus configuration for OctoCode production monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'octocode-prod'
    replica: 'prometheus-01'

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # OctoCode Application metrics
  - job_name: 'octocode-app'
    static_configs:
      - targets: ['oc_app_prod:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL metrics using postgres_exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['oc_database_prod:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'octocode-postgres'

  # Redis metrics using redis_exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['oc_redis_prod:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'octocode-redis'

  # NGINX metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['oc_nginx_prod:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker daemon metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 90d
    retention.size: 10GB
    wal-compression: true

# Remote write configuration (for external storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration (for external storage)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "username" 
#       password: "password"